-- V12 持久化团队成员（#535 / #462）：username ↔ opaque team_id。
-- 无 teams 目录表；team_id 与 OIDC groups / teamOwner 同一字符串空间。
-- V11 已被 041 占用；本刀取 V12。

CREATE TABLE IF NOT EXISTS team_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    team_id VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_team_memberships_user_team UNIQUE (username, team_id)
);

CREATE INDEX IF NOT EXISTS idx_team_memberships_username ON team_memberships (username);
