-- V13 资产治理版本快照（#537）：PUT 时可选追加全文，与 V11 变更摘要并存。
-- V12 已被 #535 占用；本刀取 V13。

CREATE TABLE IF NOT EXISTS asset_governance_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type VARCHAR(32) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    version_label VARCHAR(128),
    snapshot_text TEXT NOT NULL,
    actor VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_asset_gov_revisions_resource
    ON asset_governance_revisions (resource_type, resource_id, created_at DESC);
