-- V18 高风险审批审计（042 / #464）：策略命中与最终决策追加型事件。
-- V17 已被 #581 占用；本刀取 V18。

CREATE TABLE IF NOT EXISTS approval_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(32) NOT NULL,
    session_id VARCHAR(128),
    agent_name VARCHAR(255),
    tool_name VARCHAR(255),
    action_type VARCHAR(64),
    policy_version VARCHAR(64),
    rule_id VARCHAR(128),
    actor VARCHAR(128) NOT NULL,
    reason VARCHAR(1024),
    ttl_seconds INTEGER,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_approval_events_created ON approval_events (created_at);
CREATE INDEX IF NOT EXISTS idx_approval_events_kind ON approval_events (kind);
